- ISSUE_TEMPLATE.md
- LICENSE
- PULL_REQUEST_TEMPLATE.md
- README.md
The following documents have been added,
- ISSUE_TEMPLATE.md
- LICENSE
- PULL_REQUEST_TEMPLATE.md
The following has been updated,
- README.md
> Workflow Setup

- AUTHORS
- README.md
The authors list has been added. README.md has been updated accordingly.
> Added authors

- .gitignore
- .travis.yml
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/tests/test_arrays.py
The `OneDimensionalArray` has been completed. Some workflow changes have also been made.
> Array has been completed

- .travis.yml
- README.md
- codecov.yml
- coveragerc_travis
- requirements.txt
Fixes #15 
Some changes have been made for adding code-cov bot.
> [WIP] Added codecov

- .gitignore
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/trees/__init__.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
[1] https://en.wikipedia.org/wiki/Tree_traversal
PyDataStructs supports Binary Tree Traversals
Currently, there is a bug in `_post_order`. It needs to be fixed. Moreover `_out_order` has to be added.
> [WIP] Added binary tree traversals

- .gitignore
- pydatastructs/trees/__init__.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
[1] https://courses.cs.washington.edu/courses/cse373/06sp/handouts/lecture12.pdf
PyDataStructs now supports AVL Trees.
This PR aims at adding AVL tree. Currently its a work in progress.
> Added AVL Tree

- .travis.yml
- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/tests/test_arrays.py
PyDataStructs now support Dyanmic Arrays performing append and delete operations in amortised 
O(1) complexity.
> Added Dynamic Arrays

- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/trees/binary_trees.py
Fixes #29
Added __slots__ to all the classes
http://book.pythontips.com/en/latest/__slots__magic.html
> Added '__slots__' in classes #29

- pydatastructs/trees/__init__.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
#34 
Renamed all `Node` classes to `TreeNode`
Did not create GraphNode class yet.
> Renamed class `Node` to `TreeNode`

- pydatastructs/trees/heaps.py
Fixes #47 
Convert _heapify method from recursive to an iterative one.
> Convert _heapify method to an iterative one

- AUTHORS
- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_linked_lists.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/raises_util.py
> Added DoublyLinkedList

- pydatastructs/linear_data_structures/tests/test_arrays.py
- pydatastructs/miscellaneous_data_structures/tests/test_stack.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/trees/tests/test_space_partitioning_tree.py
Fixes #52 by asserting the raises.
changed all the raises(.....) to 
assert raises(.....)
> Test Using 'Raises' are now asserted!

- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/utils/tests/test_code_quality.py
> Added tests for code quality

- .gitignore
- README.md
- setup.py
> Added setup file

- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/miscellaneous_data_structures/tests/test_stack.py
- pydatastructs/trees/binary_trees.py
> Using DynamicOneDimensionalArray in Arraystack

- AUTHORS
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/utils/tests/test_code_quality.py
Fixes #76 
Closes #77 
* updated AUTHORS
* fixed documentation
* Added tests for presence of tabs
> Added some fixes and quality tests

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_adjacency_list.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_misc_util.py
Closes #13 
Closes #17 
Closes #34  
Framework for graph has been added. More implementations are yet to be added.
> Added Graphs

- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_adjacency_matrix.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_misc_util.py
The important point to be noted is that we have abandoned using dynamic adjacency matrices as the implementation of adjacency list is efficient i.e., time complexities are expected to be less than the theoretical ones.
> Add AdjacencyMatrix implementation for graphs

- pydatastructs/trees/space_partitioning_trees.py
Fixes #79
It fixes the incorrectness in documentation i.e. earlier there were some places in the documentation where it is said that `Stack` to implement an iterative version of recursive algorithms but in the code `Queue` is used. So this can be fixed by mentioning that `Queue` is used instead of `Stack`
> Fixed Incorrectness in Documentation

- README.md
#96 
Added Testing information for Devs in README.md
> Added Testing information for Devs in README.md

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_linked_lists.py
Added SinglyCircularLinkedList and DoublyCircularLinkedList
#49
> Issue #49 circular linked list

- README.md
- pydatastructs/linear_data_structures/linked_lists.py
Fixes #112
Improved examples in `PyDataStructs` by changing `print()` to `str()`
> [WIP] Improved examples

- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
Fixes #62 
Added algorithms for Lowest common ancestors for binary search trees.
Added tests for LCA.
> Added LCA and tests

- .gitignore
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_linked_lists.py
Fixes #124 
Now pop_left and pop_right returns the popped node.
Updated tests to keep a check on whether the value is returned.
> pop_left and pop_right returns value

- pydatastructs/__init__.py
- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_algorithms.py
- pydatastructs/utils/misc_util.py
> Added Serial BFS

- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/miscellaneous_data_structures/tests/test_queue.py
> LinkedListQueue Added

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> Added parallel BFS

- pydatastructs/graphs/algorithms.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
Closes https://github.com/codezonediitj/pydatastructs/issues/133
> Removed TODO from 3 files

- pydatastructs/graphs/graph.py
- pydatastructs/utils/misc_util.py
> Removed redundancy in Graph API

- pydatastructs/miscellaneous_data_structures/__init__.py
- pydatastructs/miscellaneous_data_structures/disjoint_set.py
- pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
> Added Disjoint set data structure

- .travis.yml
- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_adjacency_list.py
- pydatastructs/graphs/tests/test_adjacency_matrix.py
- pydatastructs/graphs/tests/test_algorithms.py
- pydatastructs/utils/misc_util.py
#137 
Other than adding Kruskal algorithm, minor changes in graph API have also been done.
> Added sequential Kurskal Algorithm

- pydatastructs/linear_data_structures/arrays.py
> Removed unnecessary aliasing of OneDimensionalArray #161

- pydatastructs/utils/tests/test_code_quality.py
https://github.com/codezonediitj/pydatastructs/pull/140#issuecomment-600264159
> Made quality tests more verbose

- pydatastructs/trees/__init__.py
- pydatastructs/trees/m_ary_trees.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
Added M_aryTreeNode for use in M_ary tree and an implementation for
M_ary Tree. The work is in reference with issue #101.
> Added implementation for M-ary tree

- pydatastructs/utils/misc_util.py
Fixes #166 
LinkedListNode documentation updated
> LinkedListNode doc updated

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/tests/test_algorithm.py
> Added parallel merge sort

- pydatastructs/trees/binary_trees.py
root_idx was not updating after #176
> SelfBalancingTree updated

- pydatastructs/linear_data_structures/arrays.py
> Changing all type() to _check_type()

- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/miscellaneous_data_structures/tests/test_queue.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/tests/test_heaps.py
Closes #131 
Minor changes have been made to interface of `BinomialHeap` and `DHeap` along with adding more implementations.
> Added more implementations of priority queue

- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/tests/test_heaps.py
#137 
* Sequential version of Prim's minimum spanning tree algorithm has been added.
* `BinomialHeap` now uses `list` instead of `DynamicOneDimensionalArray` for maintaining list of `BinomialTree` objects.
> Added sequential Prim's algorithm

- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/tests/test_arrays.py
> reversed method applied in DODA

- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
- pydatastructs/linear_data_structures/tests/test_arrays.py
- pydatastructs/utils/misc_util.py
Sorting algorithms now do not disturb positions which are out of scope of `start` and `end`. `None` is treated is infinite value. A custom comparator is introduced for the same.
ping @HarsheetKakar 
.. [1] https://github.com/codezonediitj/pydatastructs/pull/207#discussion_r397925522
> Enhancement in sorting algorithms

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
> brick_sort implemented

- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/miscellaneous_data_structures/tests/test_queue.py
Closes #137 
* In addition to adding thread based parallel Prim's algorithm, `peek` property has been added to `PriorityQueue`
> Added parallel Prim's algorithm

- pydatastructs/graphs/algorithms.py
> Docs for Prim's algorithm updated

- pydatastructs/trees/tests/test_m_ary_trees.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_misc_util.py
Fixes #19
Added tests for mary node, binomial tree node and added test_m_ary_trees.py
Added str function for mary node else it would take it as a TreeNode and raise error because there are no left and right attributes
> Added tests

- pydatastructs/linear_data_structures/linked_lists.py
Fixes #187
Added abstract methods which are common in DLL and SLL.
> Added abstract methods for LinkedList base class

- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/tests/test_adjacency_matrix.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_misc_util.py
Consistency has been introduced in the internal representations of graphs.
> Refactored graphs

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> Added Kosaraju's algorithm for SCC

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Fixes #129 
Thread based bricksort implemented
> Bricksort parallel implemented

- pydatastructs/trees/heaps.py
- pydatastructs/trees/tests/test_heaps.py
Originally in the doctstring it was written that heap expects list/tuple but it was actually taking DODA, so I have made changes to accept list, tuple and Array and derivative objects.
> heaps.py supports list, tuple and pydatastructs.Array

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Fixes #239 
Not sure on the implementation for DODA yet, further discussion is needed
> Parallel matrix multiplication algorithm added

- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/m_ary_trees.py
- pydatastructs/trees/tests/test_heaps.py
solves issue referenced in [this](https://github.com/codezonediitj/pydatastructs/pull/243#discussion_r403913053) comment
> `data` made optional in public API

- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
Fixes #234
Removed assumption rotates were making for parent of `j`.
See Issue #234
> Fixed _left_rotate and _right_rotate

- pydatastructs/trees/__init__.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
Added code for splay trees with public APIs insert, delete, splay. The work is in reference with issue #109
> Added implementation for Splay Trees.

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> DFS implemented (using the BFS API)

- pydatastructs/trees/binary_trees.py
See https://github.com/codezonediitj/pydatastructs/pull/235#issuecomment-616184252 of PR #235 
`insert` in `BinarySearchTree` assumes root as `0` and starts with `0` by initializing `prev_node` as shown below:
https://github.com/codezonediitj/pydatastructs/blob/4452dc8ad82db581f528e01f3cdc6a018ce76453/pydatastructs/trees/binary_trees.py#L221.
However, this is not a case if the tree is rotated, root can be changed from 0.
> Fixed issue with `insert` in `BinarySearchTree`

- .coveragerc
- .travis.yml
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_linked_lists.py
- pydatastructs/miscellaneous_data_structures/binomial_trees.py
- pydatastructs/miscellaneous_data_structures/disjoint_set.py
- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/m_ary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
Closes #254  
Tests that if a method which is must for child class is there in it rather than being accessed from parent class. Uses MRO to find out where the required method is.
> Quality tests for public API

- pydatastructs/trees/__init__.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
- pydatastructs/utils/tests/test_misc_util.py
Closes #215
Closes #106 
In `insert` method, it required an additional parameter, `priority` compared to the `insert` method of `BinarySearchTree`.
The `insert` method calls the insert of parent class i.e `BinarySearchTree`, then searches for the key, and converts the `TreeNode` inserted in `tree`, which is `ArrayForTrees`, to `CartesianTreeNode` and then do the rotations to satisfy heap property.
The `delete` method does the rotations first, to make the node a leaf and then calls the delete method of the parent class.
In `insert` method, it generates a priority which is not already generated before by maintaining a set by the name of `priorities`, and the calls the `insert` method of the parent class with `priority` as random number generated.
Implemented `_left_rotate` and …
> Implemeted `Treaps` and `CartesianTree`

- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/m_ary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/utils/misc_util.py
Fixes #251 
Order of parameter in docstring now matches their prototype function/class.
> Parameter order changed in docstrings

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
> Added counting sort

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> Implemented Bellman-Ford algorithm

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> Kahn's algorithm for topological sort

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
> Fixed kahn's topological sort and added parallel topological sort

- .editorconfig
Fixes #296 
added .editorconfig file
if the plugin doesn't work in vscode try with [plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig),
working fine with javascript but still having some troubles with python plugins like pylance and autopep8, if anyone knows the fix add here
> editorconfig file

- pydatastructs/__init__.py
- pydatastructs/strings/__init__.py
- pydatastructs/strings/tests/test_trie.py
- pydatastructs/strings/trie.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
> Added Trie Data Structure

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Fixes #291 
Bucket Sort is added with the buckets sorter as insertion sort
> Added Bucket Sort

- pydatastructs/trees/tests/test_binary_trees.py
Closes #294 
Replaced the testing techniques of Binary Trees where initially a manual string has to be fed; to the check of In-order and Pre-order traversals.
Since a unique tree exists with a set of In-order and Pre-order traversals, this check is comparatively easy to use as there is no need of feeding a string of the nodes, instead of which two sets of keys of nodes are fed.
> Replaced the tests of Binary Trees that need manual string matching

- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
> Minor fix in cocktail_shaker_sort

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
"Fixes #308". See
https://github.com/codezonediitj/pydatastructs/issues/308
The Longest Common Subsequence algorithm is added in the linear data structure with reference to the site https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/
Hope this works fine and if there is any issue please ping me. This is also part of SWoC contribution
> Adding Longest Common Subsequence

- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_algorithms.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_misc_util.py
This PR includes: 
- Remove unused imported modules [Anti-pattern]
- Remove unnecessary `else` / `elif` used after `return` or `raise`
- `return` statement causes the control flow to be disrupted, making the `else` / `elif` block here unnecessary. This doesn't mean you can not use it, but it is recommended to refactor this for better readability.
- Remove unnecessary use of comprehension.
- It is unnecessary to use a comprehension just to loop over the iterable and create a `list`/`set`/`dict` out of it. Python has a specialized set of tools for this task: the `list`/`set`/`dict` constructors, which are faster and more readable.
- Changing the default arguments.
- It is recommended not to use a mutable like list or dictionary as a default value to an argument. Python’s default arguments …
> potential code refactor, optimize code performance 

- pydatastructs/graphs/adjacency_list.py
> Fixed AdjacencyList.add_vertex

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/linear_data_structures/tests/test_linked_lists.py
- pydatastructs/miscellaneous_data_structures/tests/test_queue.py
- pydatastructs/miscellaneous_data_structures/tests/test_stack.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
- pydatastructs/utils/tests/test_misc_util.py
"Fixes #149". See
https://github.com/codezonediitj/pydatastructs/issues/149
The skiplist data structure is added in the linear data structure and the number of layer is dynamic based on the probability.
This set of code is the best I have ever seen for skiplist, yes this is also counted under SWoC. If you have any queries ping me.
> Adding skiplist

- pydatastructs/graphs/graph.py
Fixes #339
When the package was called, a syntax warning is shown. It has been fixed by replacing 'is' with '=='.
> Syntax Warning Fixed

- README.md
> Update guidelines in readme

- pydatastructs/miscellaneous_data_structures/disjoint_set.py
- pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
Added a method to modify the parent of set to which `key` belongs
```py
>>> dst = DisjointSetForest()
>>> dst.make_set(1)
>>> dst.make_set(2)
>>> dst.union(1, 2)
>>> dst.find_root(2).key
1
>>> dst.make_root(2)
>>> dst.find_root(2).key
2
```
> Added `make_root` in DSU 

- pydatastructs/utils/tests/test_code_quality.py
Print line number along with an error message
> Add line number in errors for easy debugging

- pydatastructs/linear_data_structures/algorithms.py
> Added returns in is_ordered docs

- README.md
- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Added the upper_bound and lower_bound functions to the algorithms library. Upper_bound returns the index of the first occurence of an element greater than value, in the given sorted OneDimensionalArray. Lower_bound returns the index of the first occurence of an element which is not less than value, in the given OneDimensionalArray.
> upper_bound and lower_bound functions added

- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Added the longest_increasing_subsequence method that returns the longest strictly increasing subsequence that can be obtained from the given array. The lower_bound function used in the implementation has been taken from #351
> Longest increasing subsequence added

- README.md
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_adjacency_list.py
- pydatastructs/graphs/tests/test_adjacency_matrix.py
- pydatastructs/linear_data_structures/arrays.py
Modified Docs to resolve discrepancies
Fixes #406 
Fixes #423
> Docs modification for better clarification 

- pydatastructs/miscellaneous_data_structures/algorithms.py
- pydatastructs/miscellaneous_data_structures/sparse_table.py
- pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py
Closes https://github.com/codezonediitj/pydatastructs/issues/422
Closes https://github.com/codezonediitj/pydatastructs/issues/409
> Made the API of ``RangeQueryStatic`` consistent

- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/pydatastructs_sphinx_graphs.ipynb
- docs/source/tutorials.rst
> Added notebook for California road network

- docs/source/index.rst
> Added salient features of PyDataStructs

- README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/pydatastructs_sphinx_graphs.ipynb
- docs/source/tutorials.rst
- pydatastructs/__init__.py
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/graph.py
- pydatastructs/graphs/tests/test_adjacency_list.py
- pydatastructs/graphs/tests/test_adjacency_matrix.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/miscellaneous_data_structures/algorithms.py
- pydatastructs/miscellaneous_data_structures/sparse_table.py
- pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py
- setup.py
> Backport 0.0.1

- pydatastructs/__init__.py
- pydatastructs/graphs/adjacency_list.py
- pydatastructs/graphs/adjacency_matrix.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/graph.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/linear_data_structures/linked_lists.py
- pydatastructs/miscellaneous_data_structures/algorithms.py
- pydatastructs/miscellaneous_data_structures/binomial_trees.py
- pydatastructs/miscellaneous_data_structures/disjoint_set.py
- pydatastructs/miscellaneous_data_structures/queue.py
- pydatastructs/miscellaneous_data_structures/sparse_table.py
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/strings/algorithms.py
- pydatastructs/strings/trie.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/heaps.py
- pydatastructs/trees/m_ary_trees.py
- pydatastructs/trees/space_partitioning_trees.py
- pydatastructs/utils/__init__.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
> Adding backend to pydatastructs APIs

- pydatastructs/linear_data_structures/arrays.py
> Fix typo in docstring of `arrays.OneDimensionalArray`

- .github/workflows/ci.yml
> Upload coverage only for python 3.8 on `ubuntu-latest`

- pydatastructs/linear_data_structures/_backend/cpp/arrays/DynamicOneDimensionalArray.hpp
- pydatastructs/miscellaneous_data_structures/__init__.py
- pydatastructs/miscellaneous_data_structures/_backend/cpp/stack/ArrayStack.hpp
- pydatastructs/miscellaneous_data_structures/_backend/cpp/stack/stack.cpp
- pydatastructs/miscellaneous_data_structures/_extensions.py
- pydatastructs/miscellaneous_data_structures/stack.py
- pydatastructs/miscellaneous_data_structures/tests/test_stack.py
- scripts/build/dummy_submodules_data.py
- setup.py
Adds cpp backend for the stack implementation.
Based on Issue #511
Work in progress
> Adding support for ``stack.ArrayStack`` in C++ backend

- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
>  Add Edmond Karp Algorithm

- .github/workflows/ci.yml
Fix some CI warnings like:
```
[test-ubuntu-py39-py310 (ubuntu-latest, 3.9)](https://github.com/codezonediitj/pydatastructs/actions/runs/5177706913/jobs/9328142768)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> upgrade CI versions

- pydatastructs/miscellaneous_data_structures/__init__.py
- pydatastructs/miscellaneous_data_structures/multiset.py
- pydatastructs/miscellaneous_data_structures/tests/test_multiset.py
> Add Multiset

- pydatastructs/linear_data_structures/_backend/cpp/algorithms/algorithms.cpp
- pydatastructs/linear_data_structures/_backend/cpp/algorithms/bubble_sort.hpp
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
> Add CPP version of bubble sort

- .github/workflows/ci.yml
- docs/source/pydatastructs/linear_data_structures/algorithms.rst
- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
- pydatastructs/utils/tests/test_code_quality.py
Fixes https://github.com/codezonediitj/pydatastructs/issues/545
Implemented Introsort.
> Implemented Introsort

- pydatastructs/trees/_backend/cpp/BinarySearchTree.hpp
- pydatastructs/trees/_backend/cpp/BinaryTreeTraversal.hpp
- pydatastructs/trees/_backend/cpp/RedBlackTree.hpp
- pydatastructs/trees/_backend/cpp/SelfBalancingBinaryTree.hpp
- pydatastructs/trees/_backend/cpp/trees.cpp
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/benchmarks/test_binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/utils/_backend/cpp/TreeNode.hpp
Add a C++ backend for Red Black Tree class.
> C++ backend for Red Black Trees

- pydatastructs/trees/_backend/cpp/BinaryIndexedTree.hpp
- pydatastructs/trees/_backend/cpp/BinarySearchTree.hpp
- pydatastructs/trees/_backend/cpp/BinaryTree.hpp
- pydatastructs/trees/_backend/cpp/BinaryTreeTraversal.hpp
- pydatastructs/trees/_backend/cpp/SplayTree.hpp
- pydatastructs/trees/_backend/cpp/trees.cpp
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
Add a C++ backend for Binary Indexed Trees class.
> C++ backend for Splay Trees

- pydatastructs/trees/_backend/cpp/BinaryTree.hpp
- pydatastructs/trees/_backend/cpp/BinaryTreeTraversal.hpp
- pydatastructs/trees/_backend/cpp/CartesianTree.hpp
- pydatastructs/trees/_backend/cpp/Treap.hpp
- pydatastructs/trees/_backend/cpp/trees.cpp
- pydatastructs/trees/binary_trees.py
- pydatastructs/trees/tests/test_binary_trees.py
- pydatastructs/utils/_backend/cpp/TreeNode.hpp
Add a C++ backend for Treap class.
Related issue: https://github.com/codezonediitj/pydatastructs/issues/550
> C++ backend for Treap

- AUTHORS
- pydatastructs/trees/_backend/cpp/AVLTree.hpp
- pydatastructs/trees/_backend/cpp/BinarySearchTree.hpp
- pydatastructs/trees/_backend/cpp/RedBlackTree.hpp
- pydatastructs/trees/_backend/cpp/SelfBalancingBinaryTree.hpp
- pydatastructs/trees/_backend/cpp/SplayTree.hpp
- pydatastructs/trees/_backend/cpp/Treap.hpp
- pydatastructs/trees/tests/test_binary_trees.py
Final additions to complete C++ backend for all trees in `binary_trees.py` file.
Added getter functions to access root_idx (index of the root) for all tree types.
This PR completes the issue: https://github.com/codezonediitj/pydatastructs/issues/550
> C++ backend for all trees in `binary_trees.py` file complete

- docs/source/authors.rst
- pydatastructs/linear_data_structures/arrays.py
- pydatastructs/trees/binary_trees.py
- pydatastructs/utils/misc_util.py
Updated the documentation by mentioning about the newly added C++ backend for binary_trees, ArrayForTrees and TreeNode class, done for GSoC 2024.
> Updated documentation

- .github/workflows/ci.yml
- environment.yml
- Modified the CI workflow (`ci.yml`) to include steps for generating and uploading code coverage reports for the C++ modules.  
- Integrated `gcov` with necessary flags for accurate coverage measurement.  
- Ensured compatibility with existing build and test processes.
> Update CI workflow for C++ coverage generation and testing

- .github/workflows/ci.yml
Recently, the windows CI has been failing due to some reason that is beyond my conscious. Hence, let's remove the command that caused the fail:
`run: conda --version`
Removal of this shouldn't matter as such.
> FIX: Windows CI

- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
Implementing Johnson's Algorithm for the All Pair Shortest Paths Problem 
Johnson's Algorithm [https://en.wikipedia.org/wiki/Johnson's_algorithm] is more efficient for the All Pair Shortest Path Problem as compared to the currently implemented Floyd-Warshall Algorithm.
Changes in this PR - 
1. Implementation of Johnson's Algorithm for Adjacency List Graphs.
2. Adds test for Johnson's Algorithm.
3. Fixes the existing tests for Floyd-Warshall Algorithm.
4. Fixes the implementation of Dijkstra to work for graphs having 0 edge weights.
> Implementing Johnson's Algorithm

- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
Implementing queue improved bellman ford algorithm.
Also known as the “shortest path faster algorithm”.
For the Bellman-Ford algorithm, each iteration requires relaxing all edges. For a vertex v that has a distance value that has not changed since the last time the edges out of v were relaxed, then there is no need to relax the edges out of v a second time.
Changes in PR:
1. Implementation of queue improved bellman ford algorithm.
2. Add tests for queue improved bellman ford algorithm.
3. Add choices for shorted path algorithm and related comment.
Related to https://github.com/codezonediitj/pydatastructs/issues/628
> feat: replace Bellman Ford Algorithm with queue version

- docs/source/pydatastructs/graphs/algorithms.rst
- pydatastructs/graphs/__init__.py
- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
Fixes #635 
This PR introduces the implementation of Tarjan's Bridge-Finding Algorithm. The key changes include:
1. Adding the find_bridges function in graphs/algorithms.py file to detect all bridges (cut-edges) in an undirected graph using Tarjan's algorithm.
2. Documentation with example usage and reference links.
3. Updating the __all__ list to expose find_bridges as part of the public API.
4. Extending the tests file to include tests for find_bridges
> Added bridge-finding algorithm

- pydatastructs/graphs/algorithms.py
- pydatastructs/graphs/tests/test_algorithms.py
Add Tarjan's strongly connected components algorithm.
Tarjan algorithm is another important algorithm for finding strongly connected components(SCCs) in directed graph. Comparing to Kosaraju algorithm, Tarjan doesn't need to generate transpose Graph.
Changes in PR:
1. Implementation of Tarjan, add in `strongly_connected_components`.
2. Add related tests for Tarjan.
3. Modify original strongly_connected_components tests. I think there is no need to return components in a specific order.
> feat: Add Tarjan's strongly connected components algorithm

- pydatastructs/utils/_backend/cpp/AdjacencyListGraphNode.hpp
- pydatastructs/utils/_backend/cpp/AdjacencyMatrixGraphNode.hpp
- pydatastructs/utils/_backend/cpp/GraphEdge.hpp
- pydatastructs/utils/_backend/cpp/GraphNode.hpp
- pydatastructs/utils/_backend/cpp/graph_utils.cpp
- pydatastructs/utils/_extensions.py
- pydatastructs/utils/misc_util.py
- pydatastructs/utils/tests/test_code_quality.py
- pydatastructs/utils/tests/test_misc_util.py
- scripts/build/dummy_submodules_data.py
This PR adds C++ backend for Graph Nodes and Edges which can be used to implement the backend for Graphs.
These changes were made - 
1. Backend for GraphNode (Abstract class), AdjacencyMatrixGraphNode, AdjacencyListGraphNode and GraphEdge is added according to their corresponding python implementations. 
2. Tests (similar to those being done for the python backend) are added for C++ backend as well.
> C++ Backend for Graph Utilities

- AUTHORS
- docs/source/pydatastructs/linear_data_structures/algorithms.rst
- pydatastructs/linear_data_structures/__init__.py
- pydatastructs/linear_data_structures/algorithms.py
- pydatastructs/linear_data_structures/tests/test_algorithms.py
Fixes #660  
This pull request introduces the Shell Sort algorithm to the sorting module, implemented in a style consistent with existing algorithms like `insertion_sort`. It includes:
- A `shell_sort` function in `algorithms.py` that supports partial sorting (`start` to `end`), custom comparators (`comp`), and backend switching (`backend`).
- Comprehensive tests in `test_algorithms.py` using `pytest` and `pytest-cov`, covering typical cases, edge cases (empty, single-element), sorted/reverse-sorted lists, duplicates, and negative numbers.
- Documentation with examples in the function's docstring, matching the project's format.
The implementation uses a simple gap sequence (`n // 2`) for clarity, with potential for future optimization using advanced sequences
> Feature Request: Implement various sorting algorithms
