pydatastructs/__init__.py, pydatastructs/linear_data_structures/arrays.py, pydatastructs/trees/__init__.py, pydatastructs/trees/binary_trees.py, pydatastructs/trees/tests/test_binary_trees.py
`BinaryTree` has been added along with `BinarySearchTree` along with tests.
There is an issue of memory leak.  Please read the docs of `delete` of `BinarySearchTree`.
=> Added Binary Tree

.travis.yml, pydatastructs/trees/__init__.py, pydatastructs/trees/space_partitioning_trees.py, pydatastructs/trees/test_space_partitioning_tree.py
Fixes #6 
PyDataStructs now supports one dimensional segment trees.
This is a work in progress PR. `query` method is to be added.
=> [WIP] Added Segment Trees

.travis.yml, README.md, codecov.yml
This PR is for testing code cov.
=> [DO NOT MERGE] Testing code cov

README.md
=> Added link for google groups

README.md
=> Corrected email id of group

.gitignore
Closes #71 
Added 2 lines that ignores files with '*.vs' extension and '.vs/' directory.
=> Added '.vs' files to '.gitignore'

PULL_REQUEST_TEMPLATE.md
removed incorrect spacing with punctuation in `PULL_REQUEST_TEMPLATE.md`
=> removed incorrect spacing with punctuation

.gitignore
=> Updated gitignore for gh-pages

pydatastructs/graphs/adjacency_matrix.py
=> Removed print statement

README.md
Fixes #236 
Add some links to data structure visualisation websites in readme.md under testing guide.
Links added: 
- https://visualgo.net/en
- https://www.cs.usfca.edu/~galles/visualization/
=> Update readme.md to include links to data structure visualisation websites

README.md
Closes #261 
Three links added under ```How to Contribute?``` of ```README``` file
=> Add links to wiki in README

README.md
Grammatical errors have been corrected  
Fixes #333
https://github.com/blog/1506-closing-issues-via-pull-requests
Please also write a comment on that issue linking back to this pull request once it is
open. -->
There were a lot of grammatical errors in the description. 
Grammatical errors have been corrected
=> Grammatical errors corrected.

.github/workflows/ci.yml, README.md
=> Update badges in `README.md`

.github/workflows/ci.yml, docs/source/authors.rst, docs/source/pydatastructs/linear_data_structures/algorithms.rst, pydatastructs/linear_data_structures/algorithms.py, pydatastructs/utils/tests/test_code_quality.py
Added bubble sort to documentation website code .
=> Added bubble sort to documentation website code.

pydatastructs/graphs/tests/test_adjacency_matrix.py
Increased the test coverage for the adjacency matrix implementation of graph data structure, by adding tests corresponding to the add_edge method.
=> Adjacency Matrix test coverage increased by adding test line

README.md, docs/source/index.rst
=> Updated installation instructions

pydatastructs/linear_data_structures/_backend/cpp/arrays/OneDimensionalArray.hpp
=> Removed debugging changes

README.md, environment.yml, pydatastructs/linear_data_structures/tests/benchmarks/test_arrays.py
- feature: Add environment.yaml to pydastructure project
- to simply install the environment for the project
- Run  following code
``` bash
conda env create --file environment.yml 
conda activate myenv
```
=> feature: Environment.yml file has been created

CODE_OF_CONDUCT.md
I just fixed some so that it's grammatically correct. The to infinitive that follows the verb fledge requires a base form so I changed 'making' to 'make'. The second one was missing a comma before and, which is referred to as the Harvard or the Oxford comma.
=> fixed some typo

pydatastructs/linear_data_structures/_backend/cpp/algorithms/algorithms.cpp, pydatastructs/linear_data_structures/_backend/cpp/algorithms/quick_sort.hpp, pydatastructs/linear_data_structures/_backend/cpp/arrays/DynamicOneDimensionalArray.hpp, pydatastructs/linear_data_structures/_backend/cpp/arrays/OneDimensionalArray.hpp, pydatastructs/linear_data_structures/_extensions.py, pydatastructs/linear_data_structures/algorithms.py, pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py, pydatastructs/linear_data_structures/tests/test_algorithms.py, pydatastructs/utils/_backend/cpp/utils.hpp, scripts/build/add_dummy_submodules.py, scripts/build/delete_dummy_submodules.py, scripts/build/dummy_submodules_data.py
=> Adding C++ backend for `pydatastructs.quick_sort`

pydatastructs/miscellaneous_data_structures/disjoint_set.py, pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
=> Implement dsu size of the group

pydatastructs/strings/algorithms.py, pydatastructs/strings/tests/test_algorithms.py
Fixes #463
Boyer Moore algorithm is implemented. It is a string matching algorithm which has 2 arguments namely: text, pattern and returns an Array of positions where pattern is found. If pattern is not found in text, then it returns an empty array.
=> Implement Boyer-Moore algorithm

pydatastructs/miscellaneous_data_structures/disjoint_set.py, pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
=> Implement groups in DSU

pydatastructs/strings/algorithms.py, pydatastructs/strings/tests/test_algorithms.py
I added an implementation of the Z-function of a string (also known as the Z-algorithm).
=> Added Z-function implementation

pydatastructs/graphs/adjacency_list.py, pydatastructs/graphs/adjacency_matrix.py, pydatastructs/graphs/algorithms.py, pydatastructs/graphs/graph.py, pydatastructs/graphs/tests/test_algorithms.py
=> Add dinic algorithm

pydatastructs/trees/binary_trees.py, pydatastructs/trees/tests/test_binary_trees.py
=> Add upper and lower bound in BST

.github/workflows/ci.yml, pydatastructs/graphs/__init__.py, pydatastructs/utils/__init__.py, pydatastructs/utils/test_util.py, pydatastructs/utils/testing_util.py
=> Add test function

pydatastructs/linear_data_structures/_backend/cpp/algorithms/algorithms.cpp, pydatastructs/linear_data_structures/_backend/cpp/algorithms/n2_square_sort.hpp, pydatastructs/linear_data_structures/algorithms.py, pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py, pydatastructs/linear_data_structures/tests/test_algorithms.py, pydatastructs/utils/testing_util.py
=> Add CPP version of selection sort

pydatastructs/linear_data_structures/_backend/cpp/algorithms/algorithms.cpp, pydatastructs/linear_data_structures/_backend/cpp/algorithms/misc_algorithms.hpp, pydatastructs/linear_data_structures/algorithms.py, pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py, pydatastructs/linear_data_structures/tests/test_algorithms.py
=> Add CPP backend for search algorithms

docs/requirements.txt, environment.yml
Changed sphinx version to v5.0 from v4.2.0
As a consequence of the above, changed myst_nb version from v0.13.1 to v0.17.2 (as myst_nb v0..13.1 doesn't support sphinx v5.0)
Fixes: https://github.com/codezonediitj/pydatastructs/issues/552
=> Version changes: sphinx and myst_nb

pydatastructs/trees/_backend/cpp/BinaryTree.hpp, pydatastructs/trees/_backend/cpp/BinaryTreeTraversal.hpp, pydatastructs/trees/_backend/cpp/CartesianTree.hpp, pydatastructs/trees/_backend/cpp/trees.cpp, pydatastructs/trees/binary_trees.py, pydatastructs/trees/tests/test_binary_trees.py, pydatastructs/utils/_backend/cpp/TreeNode.hpp
Add a C++ backend for Cartesian Trees class.
Related issue: https://github.com/codezonediitj/pydatastructs/issues/550
=> C++ backend for Cartesian Trees
